### ISSUE TITLE
Provide screenshots to each tab

### ISSUE THREAD

**Issue by JustSimplyKyle** [mrowan137/garritan-cfx-settings#1]
![image](https://github.com/user-attachments/assets/26dc3adc-e6b7-430c-8872-4120a0620642)
Having tried loading the setting, this error message appears.
If it's possible to screenshot each tab, it'll be able to allow me to apply the rough settings without updating the Aria player

**Comment by mrowan137** [comment]
Hi @JustSimplyKyle, I guess it's incompatibility due to the different versions. Here's screenshots for the file [Garritan_CFX_settings_11-11-2022.aria](https://github.com/mrowan137/garritan-cfx-settings/blob/main/cfx_configs/Garritan_CFX_settings_11-11-2022.aria), hope it helps.
<img width="768" alt="garritan-settings-1" src="https://github.com/user-attachments/assets/475c3513-2e86-4cdb-892e-a4849893e59d" />
<img width="767" alt="garritan-settings-2" src="https://github.com/user-attachments/assets/9425810d-9893-4f0d-8964-0785536fd25f" />
<img width="764" alt="garritan-settings-3" src="https://github.com/user-attachments/assets/48c56861-e50c-4dba-83ba-0f7f5d087041" />
<img width="767" alt="garittan-settings-4" src="https://github.com/user-attachments/assets/a12cd9f9-6ae7-4aa0-8ec7-c87f0c9417a1" />
<img width="764" alt="garritan-settings-5" src="https://github.com/user-attachments/assets/6ac12500-e874-4d0c-a911-6edf0b415aa1" />
